logging:
    level:
        root: info
        com.example.demo: debug

server:
    port: 8080
    shutdown: graceful

spring:
    application:
        name: application-local
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:addressDB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=3000
        username: sa
        password: 2df3652a15011bd660b3bc17807e4f3b762ff755d266580be698e0e49a111ca8
        hikari:
          pool-name: address-pool
    jpa:
        show-sql: true            
    h2:
        console:
            enabled: true
            path: /h2-console

