logging:
    level:
        root: info
        com.example.demo: debug

server:
    port: 8080
    shutdown: graceful

spring:
    application:
        name: application-local
    datasource: 
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:addressDB;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password: sa
        hikari:
          pool-name: address-pool
    jpa:
        show-sql: true            
    h2:
        console:
            enabled: true
            path: /h2-console


axon:
    axonserver:
        servers: localhost:8124
        enabled: false